# A proxy to assess scaling
To assess scaling, we consider the injection protocol for Grimsel Test Site, and the corresponding pressure values at the injection point. That is, for a given injection rate, we should expect that our model is able to reproduce a pressure (in the injection cell) that is similar to the pressure reported in the publications.

### Code setup
We are working on a custom changelist that sets the time step to `40 minutes`, with duration `[0, 40 minutes]`. The injection rate is set to a constant amount of `20 l/min`.

### Parameter setup
We include the shearzone `S1_2` and conduct injection to the borehole `INJ1`.

We turn off all gravity effects. This means that:
* No source terms (scalar and mechanics)
* Scalar dirichlet set to 0
* Mechanics neumann set to 0 except at 3 points on bottom of domain



### Expected results
From the literature (Doetsch et al 2019), for injection rates of `[10, 25] l/min`, we expect a pressure response to be in the range `[5, 9] MPa`.

In [24]:
import sys
sys.path.extend([
    '/home/haakon/mastersproject', 
    '/home/haakon/mastersproject/src/mastersproject'
])

import GTS as gts
from GTS.isc_modelling.setup import run_abstract_model
import porepy as pp
import numpy as np

In [33]:
# Prepare parameterse for run_abstract_model
model = gts.ContactMechanicsBiotISC
run_model_method = pp.run_time_dependent_model

params = {
    "length_scale": .1,
    "scalar_scale": pp.GIGA,
    "shearzone_names": ["S1_2"]
}

In [34]:
# Run the model
setup = run_abstract_model(
    model=model,
    run_model_method=run_model_method,
    params=params,
)

INFO:GTS.isc_modelling.setup:Preparing setup for simulation on 2020-03-26T12:43:17+01:00
INFO:GTS.isc_modelling.setup:Simulation parameters:
 {'bounding_box': {'xmax': 80,
                  'xmin': -20,
                  'ymax': 150,
                  'ymin': 50,
                  'zmax': 75,
                  'zmin': -25},
 'folder_name': PosixPath('/home/haakon/mastersproject/src/mastersproject/GTS/isc_modelling/results/200326/default/default_1'),
 'length_scale': 0.1,
 'mesh_args': {'mesh_size_bound': 60,
               'mesh_size_frac': 10,
               'mesh_size_min': 1.0},
 'scalar_scale': 1000000000.0,
 'shearzone_names': ['S1_2'],
 'solver': 'direct',
 'source_scalar_borehole_shearzone': {'borehole': 'INJ1', 'shearzone': 'S1_2'},
 'stress': array([[-11393046.22034133,    597621.26708787,   1842573.57669909],
       [   597621.26708787,  -8873267.78285116,   -586150.35104884],
       [  1842573.57669909,   -586150.35104884, -10733685.99680752]])}
INFO:GTS.isc_modelling.contac

INFO:GTS.isc_modelling.contact_mechanics_biot:Tagging grid of name: S1_2, and dimension 2
INFO:GTS.isc_modelling.contact_mechanics_biot:Setting non-zero source value for pressure
INFO:GTS.isc_modelling.contact_mechanics_biot:Setting non-zero source value for pressure
INFO:GTS.isc_modelling.contact_mechanics_biot:Closest cell found has distance: 20.557855
INFO:GTS.isc_modelling.contact_mechanics_biot:Closest cell found has distance: 20.557855
INFO:porepy.models.contact_mechanics_biot_model:Discretize
INFO:porepy.models.contact_mechanics_biot_model:Discretize
INFO:porepy.numerics.fv.mpsa:Split MPSA discretization into 1 parts
INFO:porepy.numerics.fv.mpsa:Split MPSA discretization into 1 parts
DEBUG:porepy.numerics.fv.mpsa:number of ncasym eliminated: 144
DEBUG:porepy.numerics.fv.mpsa:max igrad: 0.039816800195175917
INFO:porepy.numerics.fv.biot:Done with subproblem 0. Elapsed time 3.1369822025299072
INFO:porepy.numerics.fv.biot:Done with subproblem 0. Elapsed time 3.1369822025299072
DEBUG

INFO:GTS.isc_modelling.contact_mechanics_biot:Error in contact force is 2.319766e+13
INFO:GTS.isc_modelling.contact_mechanics_biot:Error in contact force is 2.319766e+13
INFO:GTS.isc_modelling.contact_mechanics_biot:Error in matrix displacement is 5.138094e-04
INFO:GTS.isc_modelling.contact_mechanics_biot:Error in matrix displacement is 5.138094e-04
INFO:GTS.isc_modelling.contact_mechanics_biot:Error in pressure is 4.419770e-02.
INFO:GTS.isc_modelling.contact_mechanics_biot:Error in pressure is 4.419770e-02.
INFO:porepy.numerics.nonlinear.nonlinear_solvers:Newton iteration number 2 of 40
INFO:porepy.numerics.nonlinear.nonlinear_solvers:Newton iteration number 2 of 40
DEBUG:porepy.numerics.interface_laws.contact_mechanics_interface_laws:Done. Elapsed time 0.013291597366333008
DEBUG:porepy.models.contact_mechanics_biot_model:Max element in A 2.69e+05
DEBUG:porepy.models.contact_mechanics_biot_model:Max 3.58e+05 and min 1.00e+00 A sum.
INFO:porepy.models.contact_mechanics_biot_model:Solve

DEBUG:porepy.numerics.interface_laws.contact_mechanics_interface_laws:Done. Elapsed time 0.03372502326965332
DEBUG:porepy.models.contact_mechanics_biot_model:Max element in A 2.69e+05
DEBUG:porepy.models.contact_mechanics_biot_model:Max 3.58e+05 and min 1.00e+00 A sum.
INFO:porepy.models.contact_mechanics_biot_model:Solve Ax=b using scipy
INFO:porepy.models.contact_mechanics_biot_model:Solve Ax=b using scipy
INFO:porepy.models.contact_mechanics_biot_model:Done. Elapsed time 0.6534180641174316
INFO:porepy.models.contact_mechanics_biot_model:Done. Elapsed time 0.6534180641174316
INFO:porepy.models.contact_mechanics_biot_model:||b-Ax|| = 2.451678418938665e-10
INFO:porepy.models.contact_mechanics_biot_model:||b-Ax|| = 2.451678418938665e-10
INFO:porepy.models.contact_mechanics_biot_model:||b-Ax|| / ||b|| = 4.833303515793338e-14
INFO:porepy.models.contact_mechanics_biot_model:||b-Ax|| / ||b|| = 4.833303515793338e-14
INFO:GTS.isc_modelling.contact_mechanics_biot:diff iter u = 1.681539e-06
INF

INFO:porepy.models.contact_mechanics_biot_model:||b-Ax|| = 4.568730202972409e-10
INFO:porepy.models.contact_mechanics_biot_model:||b-Ax|| / ||b|| = 9.006915247630055e-14
INFO:porepy.models.contact_mechanics_biot_model:||b-Ax|| / ||b|| = 9.006915247630055e-14
INFO:GTS.isc_modelling.contact_mechanics_biot:diff iter u = 6.212710e-05
INFO:GTS.isc_modelling.contact_mechanics_biot:diff iter u = 6.212710e-05
INFO:GTS.isc_modelling.contact_mechanics_biot:diff init u = 1.702270e-01
INFO:GTS.isc_modelling.contact_mechanics_biot:diff init u = 1.702270e-01
INFO:GTS.isc_modelling.contact_mechanics_biot:diff iter contact = 5.630012e+18
INFO:GTS.isc_modelling.contact_mechanics_biot:diff iter contact = 5.630012e+18
INFO:GTS.isc_modelling.contact_mechanics_biot:diff init contact = 8.173580e+16
INFO:GTS.isc_modelling.contact_mechanics_biot:diff init contact = 8.173580e+16
INFO:GTS.isc_modelling.contact_mechanics_biot:diff iter scalar = 1.750014e+14
INFO:GTS.isc_modelling.contact_mechanics_biot:diff iter

INFO:GTS.isc_modelling.contact_mechanics_biot:diff iter contact = 1.114289e+14
INFO:GTS.isc_modelling.contact_mechanics_biot:diff iter contact = 1.114289e+14
INFO:GTS.isc_modelling.contact_mechanics_biot:diff init contact = 3.753596e+15
INFO:GTS.isc_modelling.contact_mechanics_biot:diff init contact = 3.753596e+15
INFO:GTS.isc_modelling.contact_mechanics_biot:diff iter scalar = 6.737523e+09
INFO:GTS.isc_modelling.contact_mechanics_biot:diff iter scalar = 6.737523e+09
INFO:GTS.isc_modelling.contact_mechanics_biot:diff init scalar = 1.965401e+16
INFO:GTS.isc_modelling.contact_mechanics_biot:diff init scalar = 1.965401e+16
INFO:GTS.isc_modelling.contact_mechanics_biot:u converged absolutely.
INFO:GTS.isc_modelling.contact_mechanics_biot:u converged absolutely.
INFO:GTS.isc_modelling.contact_mechanics_biot:pressure converged relatively
INFO:GTS.isc_modelling.contact_mechanics_biot:pressure converged relatively
INFO:GTS.isc_modelling.contact_mechanics_biot:Error in contact force is 2.968591

In [41]:
f = setup.gb.grids_of_dimension(2)[0]
df = setup.gb.node_props(f)

g = setup.gb.grids_of_dimension(3)[0]
d = setup.gb.node_props(g)

In [28]:
state=df['state']
well = state['well']
loc = np.where(well)[0]
state['p_exp'][loc] / pp.MEGA

array([106.45306687])

In [32]:
state=df['state']
well = state['well']
loc = np.where(well)[0]
state['p_exp'][loc] / pp.MEGA

array([106.47070393])

In [36]:
state=df['state']
well = state['well']
loc = np.where(well)[0]
state['p_exp'][loc] / pp.MEGA

array([98.48821998])

In [37]:
setup.gb

Grid bucket containing 2 grids:
1 grids of dimension 3
1 grids of dimension 2

In [44]:
p_exp2 = state['p_exp'] / pp.MEGA
np.sort(p_exp2)

array([ 4.40767671,  8.58911425,  8.81202665,  9.33535998,  9.59605464,
       10.29953118, 10.32956062, 10.38993816, 10.54576518, 10.5848433 ,
       10.64216312, 10.68274871, 10.71203841, 10.74731369, 10.75837069,
       10.80083865, 10.80693201, 10.80974007, 10.86908971, 10.89234737,
       10.94464609, 10.9707235 , 10.97463278, 11.00130669, 11.00272508,
       11.05820776, 11.06385637, 11.06570477, 11.08943185, 11.09274676,
       11.15605645, 11.17980071, 11.18157882, 11.19180413, 11.19406144,
       11.19910787, 11.19938549, 11.20340204, 11.20909583, 11.27627384,
       11.32844804, 11.33204887, 12.43846052, 98.48821998])

In [47]:
# 3d Grid
state3 = d['state']
p_exp3 = state3['p_exp'] / pp.MEGA
np.where(p_exp3>30)[0]

array([11, 37])

In [49]:
g.cell_centers[:, np.where(p_exp3>30)[0]] * .1

array([[ 44.32205995,  39.88655706],
       [105.74178145, 111.58983313],
       [ 12.2387516 ,  10.64923882]])

In [55]:
well = f.cell_centers[:, loc]
well

array([[ 403.06083064],
       [1075.03563715],
       [ 126.75489484]])

In [56]:
ids, dsts = g.closest_cell(well, return_distance=True)
(ids, dsts)

(array([11]), array([44.07117768]))

In [ ]:
np.norm()